version: 2

run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple)
    - unused        # Find unused code

formatters:
  disable-all: true
  enable:
    - gofmt         # Ensure code is formatted
    - goimports     # Ensure imports are formatted

linters-settings:
  govet:
    check-shadowing: false  # Relaxed: don't check for shadowed variables
  errcheck:
    check-blank: false      # Relaxed: allow `_ = expr` to ignore errors
    check-type-assertions: false  # Relaxed: don't check type assertions
